---
title: "Homework 2"
name: Ann Gould
output:
  html_document:
    df_print: paged
github: gould-ann
---

## R Commands

1. 
```{r}
far <- c(24,15)
cel <- c()
for (i in far){
  val = ((i - 32) * 5)/9
  cel <- append(cel,val)
}
print(cel)
```

2. 

```{r}
vec200 <- integer(200)

for (i in 0:length(vec200)){
  if (i %% 2 == 1){
    vec200[i] = 3
  } else{
    vec200[i] = 1
  }
}
  
print(vec200)
```

3. 

```{r}
count = 0
for (i in 1:2001){
  if (sqrt(i) == floor(sqrt(i))){
    count <- count + 1
  }
}
  
print(count)
```

## Cars and Mileage


1. 
```{r}
# install.packages('ggplot2')
library(ggplot2)

top3 <- mpg[order(-mpg$hwy),][0:3,]
print(top3)

```

2.
```{r}
library(dplyr)

data <- mpg %>%
  count(class)

numCompact <- data[data$class == "compact", ]
print(numCompact)
```

3.
```{r}
plot(mpg$hwy)
plot(mpg$cty)
```

# EXPLANATION
Even though there are over 200 points, they all aren't that visible beacuse some points seemingly overlap with each other/appear like they are overlapping.

The trends between hwy and cty mpg are very similar... Highway mpg has a higher value than city mpg.

4.
```{r}

library(dplyr)

data <- mpg %>%
  count(class)

# do the same thing from the lab lol
plot(mpg$hwy)
plot(mpg$cty)
```


